# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'wutongguo' do
pod 'SDAutoLayout'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wutongguo

  target 'wutongguoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
